
export const CommonSubjectsReadonly = [
  "General",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Literature",
  "Computer Science",
  "Economics",
  "Psychology",
  "Philosophy",
  "Art",
  "Music",
  "Languages",
] as const;

export const CommonSubjects = [
  "General",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Literature",
  "Computer Science",
  "Economics",
  "Psychology",
  "Philosophy",
  "Art",
  "Music",
  "Languages",
];
