// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqyihrqrguhxnxqhhjhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxeWlocnFyZ3VoeG54cWhoamhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTMxMDcsImV4cCI6MjA1NDY2OTEwN30.ZS2vsztMh1X39j52A_x6EfdP5PSAZzHH6W9Aj8EXFbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);